add option for raspbee serial
WebThingsIO/zigbee-adapter pull request #249
Opened 2020-11-16 07:40 UTC by frederic34

need to add test in serialprober

2020-11-16 18:52 UTC, frederic34 commented
![image](https://user-images.githubusercontent.com/3624836/99295047-33180a00-2845-11eb-98fe-802b092deb36.png)

2020-11-16 20:22 UTC, mrstegeman requested changes

2020-11-16 20:22 UTC, mrstegeman commented on index.js
> +  allowRpiAmaSerial: false,
As mentioned in the other PR, please rename to `allowAMASerial`

2020-11-17 19:42 UTC, mrstegeman commented
Code looks good, you just need to update the serial-prober dependency.

2020-11-17 20:24 UTC, mrstegeman approved these changes

2020-11-17 20:24 UTC, merged

2020-11-17 20:27 UTC, frederic34 commented
thank's for your help