Feat/properties on aqara smartplug
WebThingsIO/zigbee-adapter pull request #258
Opened 2020-11-30 18:13 UTC by mrsteakhouse

Hi, this adds support for the energy counter attribute in a seMetering cluster.
This also depends on this: https://github.com/WebThingsIO/zcl-id/pull/2.

2020-11-30 18:15 UTC, mrsteakhouse commented
I tested this with my setup during the last weekend. The property's unit is off, since the gateway does not know about kW. Or i'm  blind enough to overlook things.

2020-11-30 18:17 UTC, mrsteakhouse commented
@chas-iot I would be happy if you can find some time to test this as well.

It would be a good idea to add a testing framework and implement regression tests somewhere in the future.

2020-12-01 01:47 UTC, chas-iot commented
> @chas-iot I would be happy if you can find some time to test this as well.

Please see https://github.com/WebThingsIO/serial-prober-node/issues/11 for why I can't test at the moment ☹️

2020-12-04 20:43 UTC, mrstegeman requested changes

2020-12-04 20:43 UTC, mrstegeman commented on zb-classifier.js
> +        '@type': 'InstantaneousPowerProperty',
Please remove the comment and the `@type` field. It will work just fine without it.

2021-01-26 17:41 UTC, mrstegeman approved these changes

2021-01-26 17:43 UTC, merged